name: spi

channels:
 - defaults
 - conda-forge

dependencies:
 - python 3.8.*
 - astropy 4.2.*
 - astroquery 0.4.*
 - jupyter 1.0.*
 - matplotlib 3.1.*
 - numpy 1.20.*
 - pandas 1.2.*
 - scipy 1.6.*
